#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#

# Klyshko Cowgear CRG related rules
cowgear-offline.x: Utils/cowgear-offline.cpp $(BOOST) $(VM) $(FHEOFFLINE) $(TINIER)
	$(CXX) -o $@ $(CFLAGS) $^ $(LDLIBS)
klyshko-hemi-offline.x: Utils/klyshko-hemi-offline.cpp $(BOOST) $(VM) $(FHEOFFLINE) $(GC_SEMI) $(OT)
	$(CXX) -o $@ $(CFLAGS) $^ $(LDLIBS)
